services:
    cdn:
        image: git.ondrejcak.sk/adam/cdn
        ports:
            - "3000:3000"
        volumes:
            - /data/appdata/cdn/files:/app/files
        environment:
            - MANAGEMENT_URI=m.localhost
            - ADMIN_TOKEN=x
            - PG_HOST=postgres
            - PG_USER=postgres
            - PG_PASS=root
            - PG_NAME=cdn
        depends_on:
            - postgres

    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: cdn
        volumes:
            - postgres-data:/var/lib/postgresql/data

    pgAdmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root

volumes:
    postgres-data:
